"""
Shared Workflow State Module

This module manages the shared state across the multi-agent workflow.
It provides a centralized data structure for agents to access and
modify workflow information.

TODO:
- Implement memory integration
- Implement persistent state storage
- Implement thread-safe state management
- Implement workflow serialization
"""

from datetime import datetime


class WorkflowState:
    """
    Centralized state management for the research workflow.

    This class maintains all shared data that agents need to access
    and modify during workflow execution.
    """

    def __init__(self, query: str = ""):
        """
        Initialize the workflow state.

        Args:
            query: Initial user research query.
        """

        # ===============================
        # Core Workflow Data
        # ===============================

        # Original user query
        self.query = query
        self.user_query = query

        # Research plan generated by PlannerAgent
        self.plan = ""

        # Research output generated by ResearchAgent
        self.research = ""
        self.research_notes = ""

        # Verification output generated by VerifierAgent
        self.verification = ""

        # Final report generated by WriterAgent
        self.final_report = ""

        # ===============================
        # Future Workflow Features
        # ===============================

        # Long-term memory
        self.memory = {}

        # Completed workflow tasks
        self.completed_tasks = []

        # Current workflow stage
        self.current_step = "Initialized"

        # Metadata
        self.metadata = {
            "created_at": datetime.now().isoformat(),
            "updated_at": datetime.now().isoformat()
        }

    def _update_timestamp(self):
        """
        Update the last modified timestamp.
        """

        self.metadata["updated_at"] = datetime.now().isoformat()

    def update_query(self, query: str):
        """
        Update the user query.

        Args:
            query: Research query.
        """

        if not query.strip():
            raise ValueError("Query cannot be empty.")

        self.query = query
        self.user_query = query

        self._update_timestamp()

    def update_plan(self, plan: str):
        """
        Store the research plan.
        """

        self.plan = plan

        self._update_timestamp()

    def add_research_note(self, note: str):
        """
        Store research information.

        Args:
            note: Research content.
        """

        self.research = note
        self.research_notes = note

        self._update_timestamp()

    def update_verification(self, verification: str):
        """
        Store verification results.
        """

        self.verification = verification

        self._update_timestamp()

    def mark_task_complete(self, task_name: str):
        """
        Mark a workflow task as completed.

        Args:
            task_name: Completed task name.
        """

        if task_name not in self.completed_tasks:
            self.completed_tasks.append(task_name)

        self.current_step = task_name

        self._update_timestamp()

    def set_final_report(self, report: str):
        """
        Store the final generated report.

        Args:
            report: Final report.
        """

        self.final_report = report

        self._update_timestamp()